ARG PROJECT_OWNER=your_gitlab_profile_name
FROM your-gitlab.com:5555/$PROJECT_OWNER/project_name/image_name:latest
WORKDIR /my_workdir
ADD some_stuff to somwhere
COPY some_other_stuff to somewhere
ENTRYPOINT start_something
